# Generated by Django 3.0.5 on 2020-04-08 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urlshortner', '0004_auto_20200407_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('my_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='urlshortner.MyURL')),
            ],
        ),
    ]
