# Generated by Django 3.0.5 on 2020-04-07 12:29

from django.db import migrations, models
import urlshortner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0003_auto_20200403_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myurl',
            name='url',
            field=models.CharField(max_length=220, validators=[urlshortner.validators.validate_url, urlshortner.validators.validate_dot_com]),
        ),
    ]
